# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='transaction_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='transaction.TransactionReal'),
        ),
    ]
