# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 16:38
from __future__ import unicode_literals

import care.fields.recurrencefield
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('groupaccount', '0002_auto_20150609_2202'),
        ('transaction', '0002_auto_modification_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('what', models.CharField(max_length=24)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('every', care.fields.recurrencefield.RecurrenceField()),
                ('last_occurrence', models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 1, 0), editable=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_buyer', to='userprofile.UserProfile')),
                ('consumers', models.ManyToManyField(related_name='rec_consumers', to='userprofile.UserProfile')),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupaccount.GroupAccount')),
            ],
        ),
        migrations.AddField(
            model_name='modification',
            name='transaction_recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification', to='transaction.TransactionRecurring'),
        ),
    ]
