# Generated by Django 2.2.17 on 2021-01-21 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_introduce_transactionrecurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='transaction_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='transaction.TransactionReal'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='transaction_recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='transaction.TransactionRecurring'),
        ),
    ]
